// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddRolesToGroupDTO
    {
        /// <summary>
        /// Initializes a new instance of the AddRolesToGroupDTO class.
        /// </summary>
        public AddRolesToGroupDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddRolesToGroupDTO class.
        /// </summary>
        public AddRolesToGroupDTO(int groupId, IList<int?> roleIds)
        {
            GroupId = groupId;
            RoleIds = roleIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupId")]
        public int GroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roleIds")]
        public IList<int?> RoleIds { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RoleIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RoleIds");
            }
        }
    }
}
