// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AddUsersToChatDTO
    {
        /// <summary>
        /// Initializes a new instance of the AddUsersToChatDTO class.
        /// </summary>
        public AddUsersToChatDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AddUsersToChatDTO class.
        /// </summary>
        public AddUsersToChatDTO(int chatId, IList<int?> userIds)
        {
            ChatId = chatId;
            UserIds = userIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chatId")]
        public int ChatId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userIds")]
        public IList<int?> UserIds { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (UserIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserIds");
            }
        }
    }
}
