// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ChannelEventDTO
    {
        /// <summary>
        /// Initializes a new instance of the ChannelEventDTO class.
        /// </summary>
        public ChannelEventDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChannelEventDTO class.
        /// </summary>
        /// <param name="type">The type of action that generated this event.
        /// Possible values include: 'NewMessage', 'UpdateMessage',
        /// 'DeleteMessage', 'RenameChannel', 'DeleteChannel'</param>
        public ChannelEventDTO(string type, System.DateTime timeOfOccurrence, GetMessageDTO message = default(GetMessageDTO), ChannelDTO channel = default(ChannelDTO))
        {
            Type = type;
            TimeOfOccurrence = timeOfOccurrence;
            Message = message;
            Channel = channel;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the type of action that generated this event. Possible
        /// values include: 'NewMessage', 'UpdateMessage', 'DeleteMessage',
        /// 'RenameChannel', 'DeleteChannel'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TimeOfOccurrence")]
        public System.DateTime TimeOfOccurrence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public GetMessageDTO Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Channel")]
        public ChannelDTO Channel { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
            if (Message != null)
            {
                Message.Validate();
            }
            if (Channel != null)
            {
                Channel.Validate();
            }
        }
    }
}
