// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateChatDTO
    {
        /// <summary>
        /// Initializes a new instance of the CreateChatDTO class.
        /// </summary>
        public CreateChatDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateChatDTO class.
        /// </summary>
        public CreateChatDTO(string chatName)
        {
            ChatName = chatName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chatName")]
        public string ChatName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ChatName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ChatName");
            }
        }
    }
}
