// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UpdateUserDTO
    {
        /// <summary>
        /// Initializes a new instance of the UpdateUserDTO class.
        /// </summary>
        public UpdateUserDTO()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UpdateUserDTO class.
        /// </summary>
        public UpdateUserDTO(string firstName = default(string), string middleInitial = default(string), string lastName = default(string), string email = default(string), bool? isDeleted = default(bool?))
        {
            FirstName = firstName;
            MiddleInitial = middleInitial;
            LastName = lastName;
            Email = email;
            IsDeleted = isDeleted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MiddleInitial")]
        public string MiddleInitial { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDeleted")]
        public bool? IsDeleted { get; set; }

    }
}
