// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UserCredentials
    {
        /// <summary>
        /// Initializes a new instance of the UserCredentials class.
        /// </summary>
        public UserCredentials()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserCredentials class.
        /// </summary>
        public UserCredentials(string email = default(string), string password = default(string))
        {
            Email = email;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

    }
}
