// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Channels.
    /// </summary>
    public static partial class ChannelsExtensions
    {
            /// <summary>
            /// Create a channel in a group
            /// </summary>
            /// <remarks>
            /// Creates a new channel in the specified group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='groupId'>
            /// </param>
            /// <param name='createChannelDTO'>
            /// The name of the channel
            /// </param>
            public static void CreateChannel(this IChannels operations, int groupId, CreateChannelDTO createChannelDTO = default(CreateChannelDTO))
            {
                operations.CreateChannelAsync(groupId, createChannelDTO).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a channel in a group
            /// </summary>
            /// <remarks>
            /// Creates a new channel in the specified group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='groupId'>
            /// </param>
            /// <param name='createChannelDTO'>
            /// The name of the channel
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CreateChannelAsync(this IChannels operations, int groupId, CreateChannelDTO createChannelDTO = default(CreateChannelDTO), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.CreateChannelWithHttpMessagesAsync(groupId, createChannelDTO, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Delete a channel from a group
            /// </summary>
            /// <remarks>
            /// Deletes the channel from the specified group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='channelId'>
            /// The id of the channel to delete
            /// </param>
            public static void DeleteChannel(this IChannels operations, int channelId)
            {
                operations.DeleteChannelAsync(channelId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a channel from a group
            /// </summary>
            /// <remarks>
            /// Deletes the channel from the specified group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='channelId'>
            /// The id of the channel to delete
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteChannelAsync(this IChannels operations, int channelId, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.DeleteChannelWithHttpMessagesAsync(channelId, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Modify a channel in a group
            /// </summary>
            /// <remarks>
            /// Modify a channel in a group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='channelId'>
            /// The id of the channel to update
            /// </param>
            /// <param name='channelName'>
            /// The new name of the channel
            /// </param>
            public static void UpdateChannel(this IChannels operations, int channelId, string channelName)
            {
                operations.UpdateChannelAsync(channelId, channelName).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Modify a channel in a group
            /// </summary>
            /// <remarks>
            /// Modify a channel in a group
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='channelId'>
            /// The id of the channel to update
            /// </param>
            /// <param name='channelName'>
            /// The new name of the channel
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateChannelAsync(this IChannels operations, int channelId, string channelName, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateChannelWithHttpMessagesAsync(channelId, channelName, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
