// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Channels operations.
    /// </summary>
    public partial interface IChannels
    {
        /// <summary>
        /// Create a channel in a group
        /// </summary>
        /// <remarks>
        /// Creates a new channel in the specified group
        /// </remarks>
        /// <param name='groupId'>
        /// </param>
        /// <param name='createChannelDTO'>
        /// The name of the channel
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        Task<HttpOperationResponse> CreateChannelWithHttpMessagesAsync(int groupId, CreateChannelDTO createChannelDTO = default(CreateChannelDTO), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Delete a channel from a group
        /// </summary>
        /// <remarks>
        /// Deletes the channel from the specified group
        /// </remarks>
        /// <param name='channelId'>
        /// The id of the channel to delete
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        Task<HttpOperationResponse> DeleteChannelWithHttpMessagesAsync(int channelId, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Modify a channel in a group
        /// </summary>
        /// <remarks>
        /// Modify a channel in a group
        /// </remarks>
        /// <param name='channelId'>
        /// The id of the channel to update
        /// </param>
        /// <param name='channelName'>
        /// The new name of the channel
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> UpdateChannelWithHttpMessagesAsync(int channelId, string channelName, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
