// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Roles.
    /// </summary>
    public static partial class RolesExtensions
    {
            /// <summary>
            /// Get roles
            /// </summary>
            /// <remarks>
            /// Get all roles in the system
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<RoleDTO> GetAllRoles(this IRoles operations)
            {
                return operations.GetAllRolesAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get roles
            /// </summary>
            /// <remarks>
            /// Get all roles in the system
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<RoleDTO>> GetAllRolesAsync(this IRoles operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllRolesWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
