// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace IO.ChaTex
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Users.
    /// </summary>
    public static partial class UsersExtensions
    {
            /// <summary>
            /// Get a list of all users registered in the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<UserDTO> GetAllUsers(this IUsers operations)
            {
                return operations.GetAllUsersAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get a list of all users registered in the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<UserDTO>> GetAllUsersAsync(this IUsers operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllUsersWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Get the the groups that a user is a member of
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<GroupDTO> GetGroupsForUser(this IUsers operations)
            {
                return operations.GetGroupsForUserAsync().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get the the groups that a user is a member of
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<GroupDTO>> GetGroupsForUserAsync(this IUsers operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetGroupsForUserWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Sign into the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userCredentials'>
            /// The user's email and password
            /// </param>
            public static string Login(this IUsers operations, UserCredentials userCredentials)
            {
                return operations.LoginAsync(userCredentials).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Sign into the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userCredentials'>
            /// The user's email and password
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> LoginAsync(this IUsers operations, UserCredentials userCredentials, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.LoginWithHttpMessagesAsync(userCredentials, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Update the information of a user in the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// The id of the user to update
            /// </param>
            /// <param name='updateUserDTO'>
            /// The new user information. All internal null values are ignored by the
            /// server
            /// </param>
            public static void UpdateUser(this IUsers operations, int userId, UpdateUserDTO updateUserDTO)
            {
                operations.UpdateUserAsync(userId, updateUserDTO).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Update the information of a user in the system
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// The id of the user to update
            /// </param>
            /// <param name='updateUserDTO'>
            /// The new user information. All internal null values are ignored by the
            /// server
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task UpdateUserAsync(this IUsers operations, int userId, UpdateUserDTO updateUserDTO, CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.UpdateUserWithHttpMessagesAsync(userId, updateUserDTO, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Get all roles for a user
            /// </summary>
            /// <remarks>
            /// Get the list of roles for a specific user
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// </param>
            public static IList<RoleDTO> GetAllUserRoles(this IUsers operations, int userId)
            {
                return operations.GetAllUserRolesAsync(userId).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get all roles for a user
            /// </summary>
            /// <remarks>
            /// Get the list of roles for a specific user
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='userId'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<RoleDTO>> GetAllUserRolesAsync(this IUsers operations, int userId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllUserRolesWithHttpMessagesAsync(userId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
